# Generated by Django 5.2 on 2025-04-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0002_file_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parent',
        ),
    ]
