# Generated by Django 5.2 on 2025-04-20 09:11

import chats_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0003_remove_message_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='metadata',
            field=models.JSONField(default=chats_app.models.str_default_dict, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.JSONField(default=chats_app.models.str_default_dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.JSONField(default=chats_app.models.str_default_dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=chats_app.models.str_default_dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=chats_app.models.str_default_dict),
        ),
    ]
