# Generated by Django 5.2 on 2025-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0004_alter_file_metadata_alter_message_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='files',
        ),
        migrations.AddField(
            model_name='conversation',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conversation',
            name='cluster_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='embedding',
            field=models.CharField(default='cohere', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='endpoint',
            field=models.CharField(default='gpt-suite', max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(default='public', max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='vector_db',
            field=models.CharField(default='pinecone', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
