# Generated by Django 5.2 on 2025-04-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0005_remove_conversation_files_conversation_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='temp_documents',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='LLMResponse',
        ),
    ]
