# Generated by Django 5.2 on 2025-04-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0006_file_temp_documents_delete_llmresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='media/files/'),
        ),
    ]
