# Generated by Django 5.2 on 2025-04-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0007_alter_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='temp_documents',
            new_name='documents',
        ),
    ]
