# Generated by Django 5.2 on 2025-04-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0009_conversation_vector_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='vector_ids',
        ),
        migrations.AddField(
            model_name='conversation',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='chats_app.file'),
        ),
    ]
